document.writeln ("Bisnis Grosir") 
document.writeln ("</br>")
document.writeln ("</br>")

document.writeln ("Apa itu bisnis grosir?")
document.writeln ("</br>")
document.writeln ("</br>")

document.writeln ("Menurut Irma Nilasari dan Sri Wilujeng, grosir adalah pihak perantara pedagang yang saling terikat kegiatan perdagangan dalam kuantitas yang banyak dan tidak bisa melayani penjualan pada konsumen tingkat akhir. Kegiatan yang dilakukan oleh grosir adalah membeli barang untuk bisa dijual lagi pada pedagang lain.")
document.writeln ("</br>")
document.writeln ("</br>")

document.writeln ("Menurut Basu Swastha, grosir adalah suatu unit usaha yang melakukan kegiatan pembelian dan penjualan kembali barang pada pihak pengecer ke pedagang lain atau pada pihak pengguna industri, pengguna lembaga, dan juga pada pengguna komersial yang tidak melakukan penjualan dengan volume yang sama pada konsumen tingkat akhir.")
document.writeln ("</br>")
document.writeln ("</br>")

document.writeln ("Perbedaan antara Grosir dan Eceran")
document.writeln ("</br>")
document.writeln ("</br>")

document.writeln ("<li>Grosir adalah penjualan barang dengan kuantitas yang banyak dan harga yang murah. Sedangkan pebisnis yang menjual barang pada konsumen tingkat akhir dalam jumlah yang kecil disebut sebagai ritel.</li> ")
document.writeln ("</br>")
document.writeln ("<li>Grosir akan menciptakan hubungan antara pihak produsen dan retail, sedangkan retail akan menciptakan hubungan antar pihak grosir dan pelanggan.</li>")
document.writeln ("</br>")
document.writeln ("<li> Perbedaan besar dari retail dan grosir adalah dari komoditas tertentunya, yakni harga grosir akan selalu lebih rendah daripada harga eceran.</li>")
document.writeln ("</br>")
document.writeln ("<li>Di dalam bisnis grosir, tidak akan ada syarat menjual barang yang menjadi keharusan di dalam bisnis retail.</li>")
document.writeln ("</br>")
document.writeln ("<li>Size atau ukuran yang terdapat pada bisnis grosir lebih besar daripada bisnis retail.</li>")
document.writeln ("</br>")
document.writeln ("<li>Di dalam bisnis retail, maka pemilik toko bisa langsung memilih barang secara bebas yang tidak mungkin bisa dilakukan di dalam bisnis grosir karena barang tersebut harus dibeli oleh grosir dalam jumlah yang banyak.</li>")
document.writeln ("</br>")
document.writeln ("<li>Modal yang diperlukan dalam bisnis grosir lebih tinggi daripada bisnis retail</li>")
document.writeln ("</br>")
document.writeln ("<li>Dalam bisnis retail, lokasi toko menjadi hal yang sangat krusial. Sedangkan pada bisnis grosir lokasi toko bukanlah masalah.</li>")
document.writeln ("</br>")
document.writeln ("<li>Ketika menjual barang secara retail, maka tampilan toko dan juga barang harus terlihat menarik agar bisa menggaet banyak pelanggan. Sedangkan dalam grosir, hal semacam itu tidak dibutuhkan.</li>")
document.writeln ("</br>")
document.writeln ("<li>Dalam bisnis grosir, mereka tidak membutuhkan iklan. Sedangkan pada bisnis retail, mereka akan sangat memerlukan iklan guna menarik banyak perhatian dari pelanggan.</li>")