document.writeln ("Bisnis Retail") 
document.writeln ("</br>")
document.writeln ("</br>")

document.writeln ("Apa itu bisnis ritel?")
document.writeln ("</br>")
document.writeln ("</br>")

document.writeln ("Menurut Philip Kotler, beliau menjelaskan bahwa arti retail yang sesungguhnya adalah penjualan eceran yang mencakup seluruh kegiatan yang melibatkan penjualan produk barang atau jasa kepada konsumen tingkat akhir untuk keperluan pribadinya.")
document.writeln ("</br>")
document.writeln ("</br>")

document.writeln ("Menurut David Gilbert, beliau berpendapat bahwa arti retail adalah seluruh upaya bisnis yang mengerahkan keahlian pemasarannya secara langsung untuk bisa memuaskan konsumen tingkat akhir dengan berdasarkan organisasi penjualan produk barang atau jasa sebagai pusat distribusinya.")
document.writeln ("</br>")
document.writeln ("</br>")

document.writeln ("Fungsi Ritel")
document.writeln ("</br>")
document.writeln ("</br>")

document.writeln ("<li>Mempermudah Konsumen dalam Mendapatkan Produk yang Diperlukan</li>")
document.writeln ("</br>")
document.writeln ("Adanya retail akan membuat konsumen tingkat akhir lebih mudah dalam mendapatkan produk yang mereka perlukan. Tanpa kehadiran bisnis retail, maka konsumen tingkat akhir akan kesulitan dalam memenuhi keperluan mereka karena mereka harus membelinya ke produsen secara langsung.")
document.writeln ("</br>")
document.writeln ("<li>Mendatangkan Keuntungan untuk Pihak Produsen dan Grosir</li>")
document.writeln ("</br>")
document.writeln ("Selain menguntungkan konsumen dalam mendapatkan keperluannya, bisnis retail juga mendatangkan keuntungan finansial yang signifikan untuk pihak produsen dan grosir. Pihak retail biasanya akan berbelanja stok produk yang banyak dari pihak grosir dan pihak grosir akan menyerahkannya pada produsen. Dana yang diterima tersebut selanjutnya bisa dimanfaatkan untuk modal produsen untuk kembali digunakan dalam proses produksi barang.")
document.writeln ("</br>")
document.writeln ("<li>Memiliki Peran dalam Mempromosikan Produk Secara Langsung</li>")
document.writeln ("</br>")
document.writeln ("Pihak retailer yang sudah membeli produk dari produsen biasanya akan mempromosikan produknya kepada konsumen dengan berbagai cara strategi iklan dan promosi. Kegiatan ini tentunya akan meningkatkan tren produk yang dikeluarkan oleh pihak produsen.")
document.writeln ("</br>")
document.writeln ("<li>Mampu Menawarkan Berbagai Jenis Barang dengan Harga yang Bervariasi</li>")
document.writeln ("</br>")
document.writeln ("Biasanya, pihak retailer akan membeli berbagai macam stok barang dari berbagai produsen yang berbeda. Harga yang mereka tawarkan pun bervariasi. Hal ini nantinya akan menimbulkan variasi pasar yang sejalan dengan adanya peningkatan rasa puas konsumen.")
